`timescale 1ns/1ps
module axi_apb_smoke_tb;
 localparam int AW=8,DW=32;logic aclk=0,aresetn=0;always #5 aclk=~aclk;
 logic[AW-1:0]awaddr,araddr,paddr;logic awvalid,awready,wvalid,wready,bvalid,bready;logic[DW-1:0]wdata,rdata,pwdata,prdata;logic[DW/8-1:0]wstrb,pstrb;logic[1:0]bresp,rresp;logic arvalid,arready,rvalid,rready;logic psel,penable,pwrite,pready,pslverr;int checks=0,errors=0;
 axi4lite_to_apb_bridge#(.ADDR_WIDTH(AW),.DATA_WIDTH(DW))dut(.aclk,.aresetn,.s_axi_awaddr(awaddr),.s_axi_awvalid(awvalid),.s_axi_awready(awready),.s_axi_wdata(wdata),.s_axi_wstrb(wstrb),.s_axi_wvalid(wvalid),.s_axi_wready(wready),.s_axi_bresp(bresp),.s_axi_bvalid(bvalid),.s_axi_bready(bready),.s_axi_araddr(araddr),.s_axi_arvalid(arvalid),.s_axi_arready(arready),.s_axi_rdata(rdata),.s_axi_rresp(rresp),.s_axi_rvalid(rvalid),.s_axi_rready(rready),.paddr,.psel,.penable,.pwrite,.pwdata,.pstrb,.prdata,.pready,.pslverr);
 apb_memory_slave#(.ADDR_WIDTH(AW),.DATA_WIDTH(DW))mem(.pclk(aclk),.presetn(aresetn),.*);
 task automatic wr(input logic[AW-1:0]addr,input logic[DW-1:0]data,input logic[3:0]strb,input int aw_delay,input int w_delay,input int ready_delay,input logic[1:0]exp=0);fork begin repeat(aw_delay)@(negedge aclk);awaddr=addr;awvalid=1;do@(posedge aclk);while(!awready);@(negedge aclk);awvalid=0;end begin repeat(w_delay)@(negedge aclk);wdata=data;wstrb=strb;wvalid=1;do@(posedge aclk);while(!wready);@(negedge aclk);wvalid=0;end join repeat(ready_delay)@(posedge aclk);@(negedge aclk);bready=1;do@(posedge aclk);while(!bvalid);checks++;if(bresp!==exp)begin errors++;$error("WRITE resp addr=%h exp=%b got=%b",addr,exp,bresp);end @(negedge aclk);bready=0;endtask
 task automatic rd(input logic[AW-1:0]addr,input logic[DW-1:0]data,input int ready_delay,input logic[1:0]exp=0);@(negedge aclk);araddr=addr;arvalid=1;do@(posedge aclk);while(!arready);@(negedge aclk);arvalid=0;repeat(ready_delay)@(posedge aclk);@(negedge aclk);rready=1;do@(posedge aclk);while(!rvalid);checks++;if(rresp!==exp)begin errors++;$error("READ resp mismatch");end if(exp==0&&rdata!==data)begin errors++;$error("READ data mismatch exp=%h got=%h",data,rdata);end @(negedge aclk);rready=0;endtask
 initial begin awaddr=0;awvalid=0;wdata=0;wstrb=0;wvalid=0;bready=0;araddr=0;arvalid=0;rready=0;$dumpfile("proof/axi_apb_wave.vcd");$dumpvars(0,axi_apb_smoke_tb);repeat(4)@(posedge aclk);@(negedge aclk);aresetn=1;
  wr(8'h04,32'h1234_abcd,4'hf,0,0,0);rd(8'h04,32'h1234_abcd,0);wr(8'h10,32'hcafe_babe,4'hf,0,2,0);wr(8'h14,32'hdead_beef,4'hf,2,0,0);wr(8'h18,32'h0102_0304,4'hf,0,0,3);rd(8'h18,32'h0102_0304,3);wr(8'h1c,32'haabb_ccdd,4'b0011,0,0,0);rd(8'h1c,32'h0000_ccdd,0);wr(8'h03,32'h55aa_55aa,4'hf,0,0,0,2'b10);rd(8'h03,0,0,2'b10);
  repeat(3)@(posedge aclk);if(errors==0)$display("AXI_APB_TEST_PASS checks=%0d errors=0",checks);else begin $display("AXI_APB_TEST_FAIL checks=%0d errors=%0d",checks,errors);$fatal(1);end $finish;end
 initial begin #1ms;$fatal(1,"AXI/APB smoke timeout");end
endmodule
